# Generated by Django 3.2.6 on 2021-09-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tokens',
            field=models.CharField(default='AAPL,', max_length=500),
        ),
    ]
